import React, { createContext, useContext, useEffect, useState, useCallback, useMemo } from 'react';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// Pre-load all translations for instant switching
const resources = {
    en: {
        translation: {
            rentalManagement: 'Universal Rental Management System',
            dashboard: 'Dashboard',
            bookings: 'Bookings',
            owners: 'Owners',
            complaints: 'Complaints',
            payments: 'Payments',
            reports: 'Reports',
            notifications: 'Notifications',
            settings: 'Settings',
            profile: 'Profile',
            logout: 'Logout',
            login: 'Login',
            register: 'Register',
            search: 'Search',
            save: 'Save',
            cancel: 'Cancel',
            edit: 'Edit',
            delete: 'Delete',
            view: 'View',
            add: 'Add',
            loading: 'Loading...',
            noData: 'No data available',
            close: 'Close',
            submit: 'Submit',
            back: 'Back',
            next: 'Next',
            previous: 'Previous',
            actions: 'Actions',
            details: 'Details',
            create: 'Create',
            update: 'Update',
            remove: 'Remove',
            confirm: 'Confirm',
            yes: 'Yes',
            no: 'No',
            adminDashboard: 'Admin Dashboard',
            ownerDashboard: 'Owner Dashboard',
            userDashboard: 'User Dashboard',
            myBookings: 'My Bookings',
            myComplaints: 'My Complaints',
            myPayments: 'My Payments',
            myRentals: 'My Rentals',
            active: 'Active',
            inactive: 'Inactive',
            pending: 'Pending',
            approved: 'Approved',
            rejected: 'Rejected',
            completed: 'Completed',
            cancelled: 'Cancelled',
            overdue: 'Overdue',
            resolved: 'Resolved',
            unresolved: 'Unresolved',
            name: 'Name',
            email: 'Email',
            phone: 'Phone',
            address: 'Address',
            description: 'Description',
            amount: 'Amount',
            date: 'Date',
            status: 'Status',
            category: 'Category',
            price: 'Price',
            duration: 'Duration',
            startDate: 'Start Date',
            endDate: 'End Date',
            totalAmount: 'Total Amount',
            paymentMethod: 'Payment Method',
            notes: 'Notes',
            successMessage: 'Operation completed successfully',
            errorMessage: 'An error occurred',
            warningMessage: 'Please check your input',
            deleteWarning: 'Are you sure you want to delete this item?',
            unsavedChanges: 'You have unsaved changes. Are you sure you want to leave?',
            totalBookings: 'Total Bookings',
            totalRevenue: 'Total Revenue',
            activeRentals: 'Active Rentals',
            pendingRequests: 'Pending Requests',
            recentActivity: 'Recent Activity',
            quickActions: 'Quick Actions',
            username: 'Username',
            password: 'Password',
            confirmPassword: 'Confirm Password',
            forgotPassword: 'Forgot Password?',
            rememberMe: 'Remember Me',
            alreadyHaveAccount: 'Already have an account?',
            dontHaveAccount: "Don't have an account?",
            resetPassword: 'Reset Password',
            sendResetLink: 'Send Reset Link',
            noResults: 'No results found',
            showing: 'Showing',
            of: 'of',
            entries: 'entries',
            filter: 'Filter',
            sortBy: 'Sort by',
            export: 'Export',
            refresh: 'Refresh',
            monthlyRevenue: 'Monthly Revenue',
            bookingTrends: 'Booking Trends',
            categoryDistribution: 'Category Distribution',
            paymentStatus: 'Payment Status',
        }
    },
    ar: {
        translation: {
            rentalManagement: 'نظام إدارة الإيجار العالمي',
            dashboard: 'لوحة التحكم',
            bookings: 'الحجوزات',
            owners: 'الملاك',
            complaints: 'الشكاوى',
            payments: 'المدفوعات',
            reports: 'التقارير',
            notifications: 'الإشعارات',
            settings: 'الإعدادات',
            profile: 'الملف الشخصي',
            logout: 'تسجيل الخروج',
            login: 'تسجيل الدخول',
            register: 'التسجيل',
            search: 'البحث',
            save: 'حفظ',
            cancel: 'إلغاء',
            edit: 'تعديل',
            delete: 'حذف',
            view: 'عرض',
            add: 'إضافة',
            loading: 'جاري التحميل...',
            noData: 'لا توجد بيانات متاحة',
            close: 'إغلاق',
            submit: 'إرسال',
            back: 'رجوع',
            next: 'التالي',
            previous: 'السابق',
            actions: 'الإجراءات',
            details: 'التفاصيل',
            create: 'إنشاء',
            update: 'تحديث',
            remove: 'إزالة',
            confirm: 'تأكيد',
            yes: 'نعم',
            no: 'لا',
            adminDashboard: 'لوحة تحكم المدير',
            ownerDashboard: 'لوحة تحكم المالك',
            userDashboard: 'لوحة تحكم المستخدم',
            myBookings: 'حجوزاتي',
            myComplaints: 'شكاوياي',
            myPayments: 'مدفوعاتي',
            myRentals: 'إيجاراتي',
            active: 'نشط',
            inactive: 'غير نشط',
            pending: 'قيد الانتظار',
            approved: 'موافق عليه',
            rejected: 'مرفوض',
            completed: 'مكتمل',
            cancelled: 'ملغي',
            overdue: 'متأخر',
            resolved: 'محلول',
            unresolved: 'غير محلول',
            name: 'الاسم',
            email: 'البريد الإلكتروني',
            phone: 'الهاتف',
            address: 'العنوان',
            description: 'الوصف',
            amount: 'المبلغ',
            date: 'التاريخ',
            status: 'الحالة',
            category: 'الفئة',
            price: 'السعر',
            duration: 'المدة',
            startDate: 'تاريخ البداية',
            endDate: 'تاريخ النهاية',
            totalAmount: 'المبلغ الإجمالي',
            paymentMethod: 'طريقة الدفع',
            notes: 'ملاحظات',
            successMessage: 'تم إكمال العملية بنجاح',
            errorMessage: 'حدث خطأ',
            warningMessage: 'يرجى التحقق من المدخلات',
            deleteWarning: 'هل أنت متأكد من حذف هذا العنصر؟',
            unsavedChanges: 'لديك تغييرات غير محفوظة. هل أنت متأكد من المغادرة؟',
            totalBookings: 'إجمالي الحجوزات',
            totalRevenue: 'إجمالي الإيرادات',
            activeRentals: 'الإيجارات النشطة',
            pendingRequests: 'الطلبات المعلقة',
            recentActivity: 'النشاط الأخير',
            quickActions: 'الإجراءات السريعة',
            username: 'اسم المستخدم',
            password: 'كلمة المرور',
            confirmPassword: 'تأكيد كلمة المرور',
            forgotPassword: 'نسيت كلمة المرور؟',
            rememberMe: 'تذكرني',
            alreadyHaveAccount: 'لديك حساب بالفعل؟',
            dontHaveAccount: 'ليس لديك حساب؟',
            resetPassword: 'إعادة تعيين كلمة المرور',
            sendResetLink: 'إرسال رابط إعادة التعيين',
            noResults: 'لا توجد نتائج',
            showing: 'عرض',
            of: 'من',
            entries: 'إدخال',
            filter: 'تصفية',
            sortBy: 'ترتيب حسب',
            export: 'تصدير',
            refresh: 'تحديث',
            monthlyRevenue: 'الإيرادات الشهرية',
            bookingTrends: 'اتجاهات الحجز',
            categoryDistribution: 'توزيع الفئات',
            paymentStatus: 'حالة الدفع',
        }
    },
    so: {
        translation: {
            rentalManagement: 'Nidaamka Maamulka Kiraynta Adduunka',
            dashboard: 'Dashboard',
            bookings: 'Kiraynta',
            owners: 'Mulkiilayaal',
            complaints: 'Shakiyada',
            payments: 'Lacag bixinta',
            reports: 'Warbixinta',
            notifications: 'Ogeysiinta',
            settings: 'Dejinta',
            profile: 'Profile',
            logout: 'Ka bixi',
            login: 'Gali',
            register: 'Diiwaan geli',
            search: 'Raadi',
            save: 'Kaydi',
            cancel: 'Jooji',
            edit: 'Wax ka beddel',
            delete: 'Tir',
            view: 'Eeg',
            add: 'Ku dar',
            loading: 'Waa la soo dejiyaa...',
            noData: 'Wax data ah ma jiro',
            close: 'Xir',
            submit: 'Dir',
            back: 'Dib u noqo',
            next: 'Midka xiga',
            previous: 'Midkii hore',
            actions: 'Falalka',
            details: 'Faahfaahinta',
            create: 'Samee',
            update: 'Cusboonaysii',
            remove: 'Ka saar',
            confirm: 'Xaqiiji',
            yes: 'Haa',
            no: 'Maya',
            adminDashboard: 'Dashboard-ka Admin-ka',
            ownerDashboard: 'Dashboard-ka Mulkiilaha',
            userDashboard: 'Dashboard-ka Isticmaalaha',
            myBookings: 'Kirayntayda',
            myComplaints: 'Shakiyadayda',
            myPayments: 'Lacag bixintayda',
            myRentals: 'Kirayntayda',
            active: 'Firfircoon',
            inactive: 'Firfircoon maaha',
            pending: 'Waa la sugayaa',
            approved: 'Waa la oggolaaday',
            rejected: 'Waa la diiday',
            completed: 'Waa la dhammaystiray',
            cancelled: 'Waa la joojiyay',
            overdue: 'Waa la dhaafay',
            resolved: 'Waa la xalliyay',
            unresolved: 'Wali lama xallin',
            name: 'Magaca',
            email: 'Emailka',
            phone: 'Telefoonka',
            address: 'Cinwaanka',
            description: 'Sharaxaada',
            amount: 'Lacagta',
            date: 'Taariikhda',
            status: 'Xaalada',
            category: 'Qaybta',
            price: 'Qiimaha',
            duration: 'Mudada',
            startDate: 'Taariikhda bilowga',
            endDate: 'Taariikhda dhammaadka',
            totalAmount: 'Wadarta lacagta',
            paymentMethod: 'Habka lacag bixinta',
            notes: 'Xusuusnowga',
            successMessage: 'Falalka waa la dhammaystiray si guul leh',
            errorMessage: 'Khalad ayaa dhacay',
            warningMessage: 'Fadlan hubi waxa aad gelisay',
            deleteWarning: 'Ma hubtaa in aad tirtayso shaygan?',
            unsavedChanges: 'Waxaad haysataa isbedelada aan la kaydin. Ma hubtaa in aad ka baxdo?',
            totalBookings: 'Wadarta kiraynta',
            totalRevenue: 'Wadarta dakhliga',
            activeRentals: 'Kiraynta firfircoon',
            pendingRequests: 'Codsiga la sugayaa',
            recentActivity: 'Falalka dambe',
            quickActions: 'Falalka degdeg ah',
            username: 'Magaca isticmaalaha',
            password: 'Furaha',
            confirmPassword: 'Xaqiiji furaha',
            forgotPassword: 'Ma illowday furaha?',
            rememberMe: 'I xusuusnow',
            alreadyHaveAccount: 'Horey u haysataa akoon?',
            dontHaveAccount: 'Ma haysataa akoon?',
            resetPassword: 'Dib u deji furaha',
            sendResetLink: 'Dir linkiga dib u dejinta',
            noResults: 'Natiijooyin ma jiraan',
            showing: 'Waxaa la muujinaya',
            of: 'ka mid ah',
            entries: 'galitaanka',
            filter: 'Shaqsi',
            sortBy: 'Kala saar si loo',
            export: 'Dhoofsi',
            refresh: 'Cusboonaysii',
            monthlyRevenue: 'Dakhliga bishii',
            bookingTrends: 'Dhaqdhaqaaqa kiraynta',
            categoryDistribution: 'Qaybinta qaybaha',
            paymentStatus: 'Xaalada lacag bixinta',
        }
    },
    tr: {
        translation: {
            rentalManagement: 'Evrensel Kiralama Yönetim Sistemi',
            dashboard: 'Kontrol Paneli',
            bookings: 'Rezervasyonlar',
            owners: 'Sahipleri',
            complaints: 'Şikayetler',
            payments: 'Ödemeler',
            reports: 'Raporlar',
            notifications: 'Bildirimler',
            settings: 'Ayarlar',
            profile: 'Profil',
            logout: 'Çıkış Yap',
            login: 'Giriş Yap',
            register: 'Kayıt Ol',
            search: 'Ara',
            save: 'Kaydet',
            cancel: 'İptal',
            edit: 'Düzenle',
            delete: 'Sil',
            view: 'Görüntüle',
            add: 'Ekle',
            loading: 'Yükleniyor...',
            noData: 'Veri bulunamadı',
            close: 'Kapat',
            submit: 'Gönder',
            back: 'Geri',
            next: 'Sonraki',
            previous: 'Önceki',
            actions: 'İşlemler',
            details: 'Detaylar',
            create: 'Oluştur',
            update: 'Güncelle',
            remove: 'Kaldır',
            confirm: 'Onayla',
            yes: 'Evet',
            no: 'Hayır',
            adminDashboard: 'Admin Kontrol Paneli',
            ownerDashboard: 'Sahip Kontrol Paneli',
            userDashboard: 'Kullanıcı Kontrol Paneli',
            myBookings: 'Rezervasyonlarım',
            myComplaints: 'Şikayetlerim',
            myPayments: 'Ödemelerim',
            myRentals: 'Kiralarım',
            active: 'Aktif',
            inactive: 'Pasif',
            pending: 'Beklemede',
            approved: 'Onaylandı',
            rejected: 'Reddedildi',
            completed: 'Tamamlandı',
            cancelled: 'İptal Edildi',
            overdue: 'Gecikmiş',
            resolved: 'Çözüldü',
            unresolved: 'Çözülmedi',
            name: 'Ad',
            email: 'E-posta',
            phone: 'Telefon',
            address: 'Adres',
            description: 'Açıklama',
            amount: 'Tutar',
            date: 'Tarih',
            status: 'Durum',
            category: 'Kategori',
            price: 'Fiyat',
            duration: 'Süre',
            startDate: 'Başlangıç Tarihi',
            endDate: 'Bitiş Tarihi',
            totalAmount: 'Toplam Tutar',
            paymentMethod: 'Ödeme Yöntemi',
            notes: 'Notlar',
            successMessage: 'İşlem başarıyla tamamlandı',
            errorMessage: 'Bir hata oluştu',
            warningMessage: 'Lütfen girdiğiniz bilgileri kontrol edin',
            deleteWarning: 'Bu öğeyi silmek istediğinizden emin misiniz?',
            unsavedChanges: 'Kaydedilmemiş değişiklikleriniz var. Ayrılmak istediğinizden emin misiniz?',
            totalBookings: 'Toplam Rezervasyon',
            totalRevenue: 'Toplam Gelir',
            activeRentals: 'Aktif Kiralamalar',
            pendingRequests: 'Bekleyen Talepler',
            recentActivity: 'Son Aktiviteler',
            quickActions: 'Hızlı İşlemler',
            username: 'Kullanıcı Adı',
            password: 'Şifre',
            confirmPassword: 'Şifreyi Onayla',
            forgotPassword: 'Şifremi Unuttum?',
            rememberMe: 'Beni Hatırla',
            alreadyHaveAccount: 'Zaten hesabınız var mı?',
            dontHaveAccount: 'Hesabınız yok mu?',
            resetPassword: 'Şifreyi Sıfırla',
            sendResetLink: 'Sıfırlama Bağlantısını Gönder',
            noResults: 'Sonuç bulunamadı',
            showing: 'Gösteriliyor',
            of: '/',
            entries: 'giriş',
            filter: 'Filtrele',
            sortBy: 'Sırala',
            export: 'Dışa Aktar',
            refresh: 'Yenile',
            monthlyRevenue: 'Aylık Gelir',
            bookingTrends: 'Rezervasyon Trendleri',
            categoryDistribution: 'Kategori Dağılımı',
            paymentStatus: 'Ödeme Durumu',
        }
    }
};

// Initialize i18next with optimized settings
i18n
    .use(initReactI18next)
    .init({
        resources,
        lng: 'en',
        fallbackLng: 'en',
        interpolation: {
            escapeValue: false,
        },
        // Performance optimizations
        keySeparator: false,
        nsSeparator: false,
        // Preload all languages
        preload: ['en', 'ar', 'so', 'tr'],
        // Cache translations
        cache: {
            enabled: true,
            expirationTime: 24 * 60 * 60 * 1000, // 24 hours
        },
        // React specific optimizations
        react: {
            useSuspense: false,
        },
    });

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [currentLanguage, setCurrentLanguage] = useState(() => {
        return localStorage.getItem('language') || 'en';
    });

    // Memoize the changeLanguage function to prevent unnecessary re-renders
    const changeLanguage = useCallback(async (language) => {
        try {
            // Change language immediately
            await i18n.changeLanguage(language);
            setCurrentLanguage(language);
            localStorage.setItem('language', language);

            // Apply RTL/LTR immediately
            const root = document.documentElement;
            if (language === 'ar') {
                root.dir = 'rtl';
                root.lang = 'ar';
                root.classList.add('rtl');
            } else {
                root.dir = 'ltr';
                root.lang = language;
                root.classList.remove('rtl');
            }

            // Force a re-render of all components using translations
            window.dispatchEvent(new CustomEvent('languageChanged', { detail: language }));
        } catch (error) {
            console.error('Error changing language:', error);
        }
    }, []);

    // Initialize language on mount
    useEffect(() => {
        changeLanguage(currentLanguage);
    }, []); // Only run once on mount

    // Memoize context value to prevent unnecessary re-renders
    const contextValue = useMemo(() => ({
        currentLanguage,
        changeLanguage,
        t: (key, options) => i18n.t(key, options),
        isRTL: currentLanguage === 'ar',
    }), [currentLanguage, changeLanguage]);

    return (
        <LanguageContext.Provider value={contextValue}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export default LanguageContext;


