"""Update category requirements with stricter validation

Revision ID: 1a9d6eb25fb0
Revises: e31728328d1f
Create Date: 2025-08-05 18:43:50.087647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a9d6eb25fb0'
down_revision = 'e31728328d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_images', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('options', sa.String(length=500), nullable=False))
        batch_op.alter_column('is_required',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('placeholder',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_requirements', schema=None) as batch_op:
        batch_op.alter_column('placeholder',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('is_required',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_column('options')
        batch_op.drop_column('max_images')

    # ### end Alembic commands ###
