"""Add RentalItem and RentalItemAnswer models

Revision ID: 49353a1dbbd6
Revises: 1a9d6eb25fb0
Create Date: 2025-08-06 00:22:28.903238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49353a1dbbd6'
down_revision = '1a9d6eb25fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_item_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_item_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['rental_item_id'], ['rental_items.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['category_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental_item_answers')
    op.drop_table('rental_items')
    # ### end Alembic commands ###
