"""Add RentalDelivery table

Revision ID: 7b464614ada2
Revises: eec9c6f84e4f
Create Date: 2025-08-10 12:50:56.121250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b464614ada2'
down_revision = 'eec9c6f84e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('confirmation_code', sa.String(length=10), nullable=False),
    sa.Column('renter_confirmed', sa.Boolean(), nullable=False),
    sa.Column('renter_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('owner_confirmed', sa.Boolean(), nullable=False),
    sa.Column('owner_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('fallback_proof', sa.Text(), nullable=True),
    sa.Column('code_expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental_deliveries')
    # ### end Alembic commands ###
