"""Add extra_config column to RentalInputField

Revision ID: aa625cff0d5c
Revises: 7116e217132b
Create Date: 2025-08-09 16:38:36.792367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = 'aa625cff0d5c'
down_revision = '7116e217132b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_input_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_config', postgresql.JSON(astext_type=Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_input_fields', schema=None) as batch_op:
        batch_op.drop_column('extra_config')

    # ### end Alembic commands ###
