"""Create RentalDelivery table with confirmation code and expiration

Revision ID: b782889467b4
Revises: 7b464614ada2
Create Date: 2025-08-10 14:27:08.742924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b782889467b4'
down_revision = '7b464614ada2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_deliveries', schema=None) as batch_op:
        batch_op.alter_column('confirmation_code',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_deliveries', schema=None) as batch_op:
        batch_op.alter_column('confirmation_code',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
