"""Add RentalInputField model

Revision ID: ccf89fe4671f
Revises: 49353a1dbbd6
Create Date: 2025-08-06 16:48:07.976057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf89fe4671f'
down_revision = '49353a1dbbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_input_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_item_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('field_key', sa.String(length=100), nullable=True),
    sa.Column('is_financial', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rental_item_id'], ['rental_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental_input_fields')
    # ### end Alembic commands ###
