"""Add contract acceptance fields to Booking

Revision ID: eec9c6f84e4f
Revises: aa625cff0d5c
Create Date: 2025-08-09 17:36:29.846357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec9c6f84e4f'
down_revision = 'aa625cff0d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_accepted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('contract_accepted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('contract_accepted_at')
        batch_op.drop_column('contract_accepted')

    # ### end Alembic commands ###
